AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SmartBoard - Serverless Transcription API

Resources:

  TranscriptionFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      Handler: app.lambda_handler
      CodeUri: ../backend/
      Timeout: 30
      MemorySize: 256
      Policies:
        - AmazonS3ReadOnlyAccess
        - AmazonDynamoDBFullAccess
        - AmazonTranscribeFullAccess
      Events:
        UploadApi:
          Type: Api
          Properties:
            Path: /upload
            Method: post
